apiVersion: apps/v1
kind: Deployment
metadata:
  name: devschool-deployment
  labels:
    app: devschool
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devschool
  template:
    metadata:
      labels:
        app: devschool
    spec:
      containers:
      - name: devschool-container
        image: <imageName>:<imageTag>
        ports:
        - containerPort: 80
